### ISSUE TITLE
Unsupported URL protocol

### ISSUE THREAD

**Issue by peterbee** [SearchSpring/haus#22]
I see the following when trying to use the newer version: v0.1.6
![image](https://cloud.githubusercontent.com/assets/2080353/13297075/c0eafb4e-daed-11e5-9616-ef2eb8ab51ef.png)

**Comment by ghellings** [comment]
Looks like I compiled against a libgit2 without ssh support.  I'll try to get that fix asap, but as a tie over, you can switch to using the https:// url in the templates dir and haus will work.

**Comment by ghellings** [comment]
I've released a new version of haus and RepoTsar that should resolve this issue.
